[package]
name = "batch-renamer"
version = "0.2.0"
authors = ["Daniel Mueller <deso@posteo.net>"]
edition = "2021"
license = "GPL-3.0-or-later"
homepage = "https://github.com/d-e-s-o/batch-renamer"
repository = "https://github.com/d-e-s-o/batch-renamer.git"
readme = "README.md"
categories = [
  "asynchronous",
  "filesystem",
  "command-line-utilities",
]
keywords = ["rename", "cli", "async", "filesystem"]
description = """
A command line utility for interactive renaming of a potentially large
number of files.
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
anyhow = "1.0.68"
grev = "0.2.0"

[dependencies]
anyhow = "1.0"
clap = { version = "4.1", features = ["derive"] }
futures = { version = "0.3", default-features = false, features = ["async-await", "std"] }
tempfile = { version = "3.3", default-features = false }
tokio = { version = "1.34", default-features = false, features = ["fs", "macros", "process", "rt"] }

[lints.rust]
deprecated-safe = "warn"
future-incompatible = "warn"
keyword-idents = "warn"
let-underscore = "warn"
missing-debug-implementations = "warn"
missing-docs = "warn"
trivial-numeric-casts = "warn"
unsafe-op-in-unsafe-fn = "warn"
unused = "warn"

[lints.clippy]
collapsible-else-if = "allow"
collapsible-if = "allow"
diverging-sub-expression = "allow"
let-and-return = "allow"
let-unit-value = "allow"
module-inception = "allow"
type-complexity = "allow"
absolute-paths = "warn"
allow-attributes = "warn"
cast-sign-loss = "warn"
clone-on-ref-ptr = "warn"
dbg-macro = "warn"
debug-assert-with-mut-call = "warn"
derive-partial-eq-without-eq = "warn"
doc-markdown = "warn"
indexing-slicing = "warn"
invalid-upcast-comparisons = "warn"
join-absolute-paths = "warn"
large-enum-variant = "warn"
let-underscore-must-use = "warn"
lossy-float-literal = "warn"
multiple-unsafe-ops-per-block = "warn"
panic-in-result-fn = "warn"
ptr-as-ptr = "warn"
redundant-closure-for-method-calls = "warn"
string-slice = "warn"
unchecked-time-subtraction = "warn"
undocumented-unsafe-blocks = "warn"
uninlined-format-args = "warn"
use-self = "warn"
wildcard-imports = "warn"
